# Generated by Django 5.2.12 on 2026-04-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_urlping_error_snapshot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="urlping",
            name="error_snapshot",
        ),
        migrations.AddField(
            model_name="urlping",
            name="error",
            field=models.TextField(blank=True, null=True),
        ),
    ]
