# Generated by Django 5.2.12 on 2026-04-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_urlping_error_snapshot_urlping_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="urlping",
            name="s3_key",
            field=models.TextField(blank=True, null=True),
        ),
    ]
