# Generated by Django 5.2.12 on 2026-04-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_urlping_s3_key"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="urlping",
            index=models.Index(
                fields=["url", "-time"], name="api_urlping_url_id_45ebac_idx"
            ),
        ),
    ]
