# Generated by Django 5.0.3 on 2026-04-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_urlping_api_urlping_url_id_45ebac_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="url",
            field=models.URLField(max_length=100, unique=True),
        ),
    ]
