from django.core.management.base import BaseCommand

from api.models import Url


class Command(BaseCommand):
    help = "Seed URLs"

    def handle(self, *args, **kwargs):
        urls = [
            "https://www.google.com",
            "https://www.youtube.com",
            "https://www.facebook.com",
            "https://www.instagram.com",
            "https://www.twitter.com",
            "https://www.linkedin.com",
            "https://www.wikipedia.org",
            "https://www.reddit.com",
            "https://www.amazon.com",
            "https://www.netflix.com",
            "https://www.microsoft.com",
            "https://www.apple.com",
            "https://www.github.com",
            "https://www.stackoverflow.com",
            "https://www.medium.com",
            "https://www.quora.com",
            "https://www.bbc.com",
            "https://www.cnn.com",
            "https://www.nytimes.com",
            "https://www.yahoo.com",
            "https://www.bing.com",
            "https://www.duckduckgo.com",
            "https://www.twitch.tv",
            "https://www.discord.com",
            "https://www.spotify.com",
            "https://www.paypal.com",
            "https://www.dropbox.com",
            "https://www.slack.com",
            "https://www.zoom.us",
            "https://www.adobe.com",
            "https://www.canva.com",
            "https://www.pinterest.com",
            "https://www.ebay.com",
            "https://www.imdb.com",
            "https://www.fandom.com",
            "https://www.salesforce.com",
            "https://www.shopify.com",
            "https://www.heroku.com",
            "https://www.digitalocean.com",
            "https://www.cloudflare.com",
            "https://www.openai.com",
            "https://chat.openai.com",
            "https://platform.openai.com",
            "https://www.khanacademy.org",
            "https://www.coursera.org",
            "https://www.udemy.com",
            "https://www.edx.org",
            "https://www.freecodecamp.org",
            "https://www.w3schools.com",
            "https://developer.mozilla.org",
            "https://react.dev",
            "https://vuejs.org",
            "https://angular.io",
            "https://nodejs.org",
            "https://expressjs.com",
            "https://djangoproject.com",
            "https://flask.palletsprojects.com",
            "https://spring.io",
            "https://rubyonrails.org",
            "https://laravel.com",
            "https://tailwindcss.com",
            "https://getbootstrap.com",
            "https://material-ui.com",
            "https://mui.com",
            "https://vercel.com",
            "https://netlify.com",
            "https://firebase.google.com",
            "https://supabase.com",
            "https://postgresql.org",
            "https://mysql.com",
            "https://mongodb.com",
            "https://redis.io",
            "https://sqlite.org",
            "https://figma.com",
            "https://dribbble.com",
            "https://behance.net",
            "https://unsplash.com",
            "https://pexels.com",
            "https://pixabay.com",
            "https://weather.com",
            "https://timeanddate.com",
            "https://worldbank.org",
            "https://who.int",
            "https://nasa.gov",
            "https://esa.int",
            "https://stackoverflow.blog",
            "https://hashnode.com",
            "https://dev.to",
            "https://producthunt.com",
            "https://techcrunch.com",
            "https://thenextweb.com",
            "https://arxiv.org",
            "https://ieee.org",
            "https://acm.org",
            "https://bbc.co.uk",
            "https://guardian.co.uk",
            "https://aljazeera.com",
            "https://espn.com",
            "https://cricinfo.com",
        ]

        urls_to_create = [Url(url=u) for u in urls]
        Url.objects.bulk_create(urls_to_create, ignore_conflicts=True)

        self.stdout.write(self.style.SUCCESS(f"{len(urls)} URLs inserted"))
